language: go

services:
  - docker

go:
 - 1.3.3
 - 1.4.2
 - 1.5.1
 - release
 - tip

env:
  global:
    #DOCKER_EMAIL
    #DOCKER_USERNAME
    #DOCKER_PASSWORD

script:
 - go test -v ./...

before_deploy:
 - docker build -t gregdistefano/go-fileshare .
 - docker push gregdisstefano/go-fileshare
