language: go
services:
- docker
go:
- tip
env:
  global:
  - CONFIG_FILE=config/config.travis.yaml

before_install:
- mkdir files
- go get github.com/stretchr/testify/assert
- go get github.com/etcinit/speedbump/ginbump
- go get github.com/etcinit/speedbump
- go get github.com/dustin/go-humanize
- openssl aes-256-cbc -K $encrypted_1c5f6eb52035_key -iv $encrypted_1c5f6eb52035_iv
  -in config/pk-APKAIWSICRWRZP4KRDWA.pem.enc -out config/pk-APKAIWSICRWRZP4KRDWA.pem -d

script:
- go test -v ./...
- go build .

after_script:
- docker login --email=$DOCKER_EMAIL --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
- docker build -t gregdistefano/go-fileshare:latest .
- docker tag gregdistefano/go-fileshare:latest latest
- docker push gregdistefano/go-fileshare:latest
