language: go
services:
- docker
go:
- release
- tip
env:
  global:
  - CONFIG_FILE=config/config.travis.json

before_install:
- mkdir files
- go get github.com/stretchr/testify/assert
- openssl aes-256-cbc -K $encrypted_1c5f6eb52035_key -iv $encrypted_1c5f6eb52035_iv
  -in config/pk-APKAIWSICRWRZP4KRDWA.pem.enc -out config/pk-APKAIWSICRWRZP4KRDWA.pem -d

script:
- go test -v ./...
before_deploy:
- docker build -t gregdistefano/go-fileshare .
- docker push gregdisstefano/go-fileshare

