---
aws:
  bucket: greg-filestorage
  cf_key_id: APKAIWSICRWRZP4KRDWA
  cf_key_location: ./config/pk-APKAIWSICRWRZP4KRDWA.pem
  cf_url: dssdldrogwhnn.cloudfront.net
  region: eu-west-1


port: 127.0.0.1:8080
file_check_freq: 1
max_downloads: 10
delete_key_size: 8
key_size: 4
domain: http://127.0.0.1:8080
max_file_size: 25000000
delete_after_seconds: 30 
