---
aws:
  bucket: greg-filestorage
  cf_key_id: APKAIWSICRWRZP4KRDWA
  cf_key_location: ./config/pk-APKAIWSICRWRZP4KRDWA.pem
  cf_url: dssdldrogwhnn.cloudfront.net
  region: eu-west-1

port: 127.0.0.1:8080
file_check_freq: 60
max_downloads: 10
delete_key_size: 8
key_size: 6
domain: "grabfile.io"
max_file_size: 2000000000
delete_after_seconds: 120
